services:          #default synxtax
  frontendnginxfirst:        #naming convention for container
    build: /root/docker-healet/ #location of the docker file
    ports:     #port mapping my container to host port 
      - '80:80'  
    container_name: contfirst  #providing name to container
    volumes:   #mounting persistent volume of my host to container
      - myapp:/var/www/html/
    network_mode:   #providing network mode
        bridge

volumes: 
      myapp: